# Generated by Django 5.1a1 on 2024-11-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crianca",
            name="bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="cep",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="numero",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="rua",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
