# Generated by Django 5.1.3 on 2024-11-09 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_crianca_bairro_alter_crianca_cep_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="crianca",
            name="escola",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="numero",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="tamanho_camiseta",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="telefone_responsavel",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.CreateModel(
            name="Participacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="INSCRITA", max_length=20)),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.atividade"
                    ),
                ),
                (
                    "nome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.crianca"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Participações das crianças",
            },
        ),
    ]
