# Generated by Django 5.1.3 on 2024-11-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_atividade_alter_crianca_escola_alter_crianca_numero_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atividade",
            options={"verbose_name_plural": "Cadastro das atividades"},
        ),
        migrations.AlterModelOptions(
            name="crianca",
            options={"verbose_name_plural": "Cadastro das crianças"},
        ),
    ]
