# Generated by Django 5.1.3 on 2024-11-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_atividade_options_alter_crianca_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, null=True)),
                ("telefone", models.IntegerField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("profissao", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "local_de_trabalho",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "grau_de_parentesco",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crianca",
            name="responsavel",
            field=models.ManyToManyField(to="app.responsavel"),
        ),
    ]
