# Generated by Django 5.1.3 on 2024-11-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pendente', max_length=50)),
                ('link_visualizacao', models.URLField(blank=True, max_length=255, null=True)),
                ('imagem_qrcode', models.TextField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('txid', models.TextField(blank=True, default=0)),
                ('id_loc', models.TextField(default=0)),
            ],
        ),
    ]
