# Generated by Django 5.1.3 on 2024-11-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='id_loc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
