# Generated by Django 5.1.3 on 2024-11-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pix', '0002_alter_pagamento_id_loc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AddField(
            model_name='pagamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-08 14:30+00:00', verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='solicitacao_pagador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Solicitação ao Pagador'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF do Devedor'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id_loc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Localização'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='imagem_qrcode',
            field=models.TextField(blank=True, null=True, verbose_name='Imagem do QR Code'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='link_visualizacao',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Visualização'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Devedor'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='txid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Txid do Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Cobrança'),
        ),
    ]
