# Generated by Django 5.1.3 on 2024-11-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pix', '0004_alter_pagamento_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='solicitacao_pagador',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='email',
            field=models.EmailField(default='ongamigo@esperanca', max_length=254),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
