# Generated by Django 5.1.3 on 2024-11-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crianca",
            name="filial",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="myapp.filial",
            ),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="necessidade_especial",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="myapp.necessidade_especial",
            ),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="turno",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Matutino", "Matutino"),
                    ("Vespetino", "Vespetino"),
                    ("Noturno", "Noturno"),
                    ("Integral", "Integral"),
                ],
                max_length=9,
                null=True,
            ),
        ),
    ]
