# Generated by Django 5.1.3 on 2024-11-10 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_crianca_necessidade_especial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crianca",
            name="necessidade_especial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.necessidade_especial",
            ),
        ),
    ]
