# Generated by Django 5.1.3 on 2024-11-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_crianca_necessidade_especial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crianca",
            name="filial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="myapp.filial",
            ),
        ),
        migrations.AlterField(
            model_name="filial",
            name="nome_filial",
            field=models.CharField(
                blank=True,
                choices=[("ERICH BELZ", "ERICH BELZ"), ("VILA JENSEN", "VILA JENSEN")],
                max_length=100,
                null=True,
            ),
        ),
    ]
